export const start_game = {
  entity_id: '-8589934591',
  runtime_entity_id: '1',
  player_gamemode: 'fallback',
  player_position: {
    x: 0.5,
    y: 32769.62109375,
    z: 0.5,
  },
  rotation: {
    x: 0,
    z: 0,
  },
  seed: [
    3071130681,
    2024568913,
  ],
  biome_type: 0,
  biome_name: 'minecraft:plains',
  dimension: 'overworld',
  generator: 1,
  world_gamemode: 'survival',
  hardcore: false,
  difficulty: 1,
  spawn_position: {
    x: 0,
    y: 32767,
    z: 0,
  },
  achievements_disabled: true,
  editor_world_type: 'not_editor',
  created_in_editor: false,
  exported_from_editor: false,
  day_cycle_stop_time: 1219,
  edu_offer: 0,
  edu_features_enabled: false,
  edu_product_uuid: '',
  rain_level: 0,
  lightning_level: 0,
  has_confirmed_platform_locked_content: false,
  is_multiplayer: true,
  broadcast_to_lan: true,
  xbox_live_broadcast_mode: 6,
  platform_broadcast_mode: 6,
  enable_commands: true,
  is_texturepacks_required: false,
  gamerules: [],
  experiments: [],
  experiments_previously_used: false,
  bonus_chest: false,
  map_enabled: false,
  permission_level: 4,
  server_chunk_tick_range: 4,
  has_locked_behavior_pack: false,
  has_locked_resource_pack: false,
  is_from_locked_world_template: false,
  msa_gamertags_only: true,
  is_from_world_template: false,
  is_world_template_option_locked: false,
  only_spawn_v1_villagers: false,
  persona_disabled: false,
  custom_skins_disabled: false,
  emote_chat_muted: false,
  game_version: '*',
  limited_world_width: 16,
  limited_world_length: 16,
  is_new_nether: false,
  edu_resource_uri: {
    button_name: '',
    link_uri: '',
  },
  experimental_gameplay_override: false,
  chat_restriction_level: 'none',
  disable_player_interactions: false,
  server_identifier: '',
  world_identifier: '',
  scenario_identifier: '',
  owner_identifier: '',
  level_id: 'Bedrock level',
  world_name: 'Bedrock level',
  premium_world_template_id: '00000000-0000-0000-0000-000000000000',
  is_trial: false,
  rewind_history_size: 40,
  server_authoritative_block_breaking: true,
  current_tick: [
    0,
    1218,
  ],
  enchantment_seed: 1236130570,
  block_properties: [],
  multiplayer_correlation_id: '<raknet>a2f1-c28f-0808-d27c',
  server_authoritative_inventory: true,
  engine: '1.21.120',
  property_data: {
    type: 'compound',
    name: '',
    value: {},
  },
  block_pallette_checksum: [],
  world_template_id: '00000000-0000-0000-0000-000000000000',
  client_side_generation: false,
  block_network_ids_are_hashes: true,
  tick_death_systems: false,
  server_controlled_sound: true,
}